---
- hosts: test-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

 - name: To remove existing insure-me container
    command: sudo docker rm -f my-insure 

  - name: Deploy Docker Container
    command: docker run -itd -p 8081:8081 --name my-insure jyothsna2047/insure-me:1.0
